defaults:
  - _self_
  - nnet: SPDNet
  - dataset: RADAR # HDM05, RADAR
  - override hydra/launcher: joblib
fit:
  epochs: 200
  batch_size: 30
  threadnum: 2
  is_writer: True
  cycle: 50
  seed: 1024
  is_save: True
  folds: 10

hydra:
  run:
    dir: ./outputs/${dataset.name}
  sweep:
    dir: ./outputs/${dataset.name}
    subdir: '.'
  launcher:
    n_jobs: -1
  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        filename: default.log
