model:
    model_type: SPDNet
    init_mode: svd #uniform,svd
    architecture: [20,16,8]
    classifier: LogEigMLR #LogEigMLR, SPDMLR
    metric: SPDLogCholeskyMetric #SPDLogCholeskyMetric,SPDLogCholeskyMetric
    power: 1.
    alpha: 1.0
    beta: 0.0
optimizer:
    mode: AMSGRAD #AMSGRAD,SGD,ADAM
    lr: 1e-2
    weight_decay: 0