name: TSMNet
inputtype: ${torchdtype:float32}
model:
    _target_: spdnets.models.TSMNetMLR
    temporal_filters: 4
    spatial_filters: 40
    subspacedims: 20
    bnorm: null
    bnorm_dispersion: null
    classifier: LogEigMLR #LogEigMLR, SPDMLR
    metric: SPDLogCholeskyMetric #SPDLogCholeskyMetric,SPDLogCholeskyMetric
    power: 1.
    alpha: 1.0
    beta: 0.0
optimizer:
    _target_: geoopt.optim.RiemannianAdam
    amsgrad: True
    weight_decay: 1e-4
    lr: 1e-3
    param_groups:
        -
            - 'spdnet.*.W'
            - weight_decay: 0
scheduler:
    _target_: spdnets.batchnorm.DummyScheduler